Repository libertempo/web, pull requests merged in 2018-03, with the labels that each got.

#572 fix(Utilisateur::getListUtilisateurByGroupeIds): unicité des utilisateurs retournés
  App/ProtoControllers/Groupe/Utilisateur.php
Labels: Bug, Métier

#599 feat(calendrier): afficher les groupes listés dans l'ordre alphabétique
  App/ProtoControllers/Groupe.php
Labels: Amélioration, Métier

#603 tri alphabétique des utilisateurs et des responsables sur la page de modification d'un groupe
  App/ProtoControllers/Responsable.php
  App/ProtoControllers/Utilisateur.php
Labels: Amélioration, Métier

#596 fix(Utilisateur::getListeGroupesVisibles): correctif pour merger correctement les arrays
  App/ProtoControllers/Utilisateur.php
Labels: Amélioration, Métier

#601 Affichage des utilisateurs au format "nom prénom"
  App/ProtoControllers/Utilisateur.php
Labels: Amélioration, Métier

#576 feat(calendrier): affichage des responsables avant les membres d'un groupe
  App/Views/Calendrier/Mois.php
  Public/Assets/Css/reboot.css
  calendrier.php
Labels: Amélioration, Métier

#573 fix(Responsable::getListResponsableByGroupeIds): récupération de tous les responsables
  App/ProtoControllers/Groupe/Responsable.php
Labels: Amélioration, Métier

#612 [PHP 7.2] correction bug fetch_all()
  includes/SQL.php
Labels: Bug

#611 LT <3 Codacy
  App/Libraries/ANotification.php
  App/ProtoControllers/Employe/AHeure.php
  App/ProtoControllers/Employe/Heure/Additionnelle.php
  App/ProtoControllers/Employe/Heure/Repos.php
  App/ProtoControllers/HautResponsable/Planning/Creneau.php
  App/ProtoControllers/Responsable.php
  App/ProtoControllers/Responsable/Traitement/Conge.php
  App/Views/Calendrier/Mois.php
  Public/template/error_bottom.php
  admin/Fonctions.php
  config/Fonctions.php
  config/index.php
  edition/Fonctions.php
  export/Fonctions.php
  fonctions_calcul.php
  fonctions_conges.php
  hr/Fonctions.php
  includes/SQL.php
  includes/fonction.php
  includes/fonction_config.php
  includes/lang_profile.php
  includes/plugins.php
  includes/plugins/cet/add_textbox_users.php
  index.php
  install/Fonctions.php
  install/index.php
  install/mise_a_jour.php
  library/authLDAP.php
  responsable/Fonctions.php
  responsable/resp_ajout_conges.php
  utilisateur/Fonctions.php
Labels: Amélioration, Système
