Repository libertempo/web, pull requests merged in 2018-05, with the labels that each got.

#628 Reject crawlers by default
  robots.txt
Labels: En attente, Système, À relire, À tester

#644 Empêcher la prise d'absence dans le passé
  Public/Assets/Js/reboot.js
  utilisateur/Fonctions.php
Labels: Beta, Bug, Métier

#651 Responsable en premier + correction defaut multi groupe
  App/ProtoControllers/Groupe/Responsable.php
  App/ProtoControllers/HautResponsable/Utilisateur.php
  App/Views/Calendrier/Mois.php
  calendrier.php
Labels: Beta, Bug, Métier

#649 Connexion obligatoire à l'API
  includes/fonction.php
  index.php
Labels: Beta, Bug, Système

#645 XSS en mode HR
  hr/Fonctions.php
Labels: Beta, Bug, Système, Sécurité
