Repository libertempo/web, pull requests merged in 2018-06, with the labels that each got.

#647 Calcul des dates féries non asujettis aux changements d'heures
  Tests/Units/hr/Fonctions.php
  hr/Fonctions.php
Labels: Bug, Métier

#664 en tête formulaire de validation des congés et heures par le responsable. Fix #655
  App/ProtoControllers/Responsable/Traitement/Conge.php
  App/Views/Responsable/Validation/ListeConges.php
  App/Views/Responsable/Validation/ListeHeures.php
  responsable/resp_traitement_demandes.php
  responsable/resp_traitement_heures_additionnelles.php
  responsable/resp_traitement_heures_repos.php
Labels: Bug

#667 Correction bug reliquats fix #639
  App/ProtoControllers/Responsable/Traitement/Conge.php
Labels: Beta, Bug, Métier, À retoucher
