Repository libertempo/web, pull requests merged in 2018-11, with the labels that each got.

#742 [installation] make check : controle des prérequis
  App/Tools/check
  App/Tools/createHR
  App/Tools/libraries
  App/Tools/setup
  Makefile
Labels: Système, À documenter

#745 [installation] pas d'erreur si pas d'update
  App/Tools/update
Labels: Amélioration, Système

#748 Max is never empty
  hr/Fonctions.php
Labels: Bug
