Repository libertempo/web, pull requests merged in 2018-09, with the labels that each got.

#694 Correction connexion LDAP (et consorts)
  App/Libraries/Ldap.php
  App/ProtoControllers/HautResponsable/Utilisateur.php
Labels: Bug, Important, LDAP/AD/CAS/SSO

#691 Ne pas modifier / supprimer les types d'absence natifs : partie 1
  App/Libraries/ApiClient.php
  App/Patchs/Maj/1.12.1.sql
  App/Views/Configuration/Type_Absence/Liste.php
  config/Fonctions.php
  config/config_type_absence.php
  includes/fonctions_conges.php
Labels: Amélioration, Métier, À documenter

#695 [CLI] Création d'un utilisateur haut responsable et administrateur
  App/Patchs/Maj/1.12.0.sql
  App/Tools/createHR
  App/Tools/libraries
  Makefile
Labels: Fonctionnalité, Système, À documenter

#713 Définition de la config API à chaque màj
  App/Patchs/Maj/1.12.0.sql
  App/Tools/libraries
  App/Tools/setup
  App/Tools/update
Labels: Bug, Système
