Repository libertempo/web, pull requests merged in 2018-12, with the labels that each got.

#753 Suppression plugin
  App/Patchs/Maj/1.13.0.sql
  App/Tools/update
  Public/Assets/Css/reboot.css
  config/Fonctions.php
  includes/define.php
  includes/fonction.php
  includes/plugins.php
  includes/plugins/cet/add_column_hr.php
  includes/plugins/cet/add_textbox_users.php
  includes/plugins/cet/allfilestoinclude.php
  includes/plugins/cet/css/bulles.css
  includes/plugins/cet/plugin_active.php
  includes/plugins/cet/plugin_inactive.php
  includes/plugins/cet/plugin_install.php
  includes/plugins/cet/plugin_uninstall.php
  locale/fr_FR/LC_MESSAGES/php-conges.po
Labels: Amélioration, Métier

#757 [Bug] Correctly merge typeAbsence array
  hr/Fonctions.php
Labels: Beta, Bug

#754 [make] paramétrage de la configuration
  App/Tools/configure
  Makefile
Labels: Amélioration, Système

#758 Sauvegarde et suppression en CLI seulement
  App/Tools/destroy
  App/Tools/libraries
  App/Tools/restore
  App/Tools/savedb
  App/Tools/setup
  App/Tools/update
  Makefile
  Public/index.php
  Public/template/menu_header.php
  admin/Fonctions.php
  admin/admin_admin-group.php
  admin/admin_ajout_group.php
  admin/admin_db_sauve.php
  admin/admin_index.php
  admin/admin_modif_group.php
  admin/admin_suppr_group.php
  includes/define.php
  includes/fonctions_conges.php
Labels: Fonctionnalité, Système, security

#761 [WIP] Show SQL et compagnies
  .gitignore
  App/ProtoControllers/Groupe/Gestion.php
  App/ProtoControllers/Groupe/Responsable.php
  App/ProtoControllers/Utilisateur.php
  App/Tools/libraries
  App/Views/JourFerie/Liste.php
  App/Views/Responsable/AjoutAbsence.php
  Public/Assets/Css/reboot.css
  Public/template/bottom.php
  Public/template/error_bottom.php
  Public/template/error_header.php
  Public/template/header.php
  Public/template/login_bottom.php
  Public/template/login_header.php
  Public/template/menu_bottom.php
  Public/template/menu_header.php
  Public/template/popup_bottom.php
  Public/template/popup_header.php
  Tests/jeutest.sql
  Tests/jeutestcomplet-v1.9.sql
  Tests/script_jeutest.php
  config/Fonctions.php
  config/index.php
  edition/Fonctions.php
  export/Fonctions.php
  hr/Fonctions.php
  hr/hr_index.php
  includes/SQL.php
  includes/define.php
  includes/fonction.php
  includes/fonction_config.php
  includes/fonctions_calcul.php
  includes/fonctions_conges.php
  index.php
  responsable/Fonctions.php
  responsable/resp_index.php
  utilisateur/Fonctions.php
  utilisateur/user_index.php
Labels: Amélioration, Système, À relire

#760 Première utilisation de VueJS
  App/ProtoControllers/Utilisateur.php
  App/Tools/destroy
  App/Tools/libraries
  App/Views/Configuration/Type_Absence/Liste.php
  App/Views/Planning/Formulaire/Responsable_Edit.php
  App/Views/Planning/Liste.php
  Public/Assets/Css/reboot.css
  Public/index.php
  Public/template/header.php
  Public/template/menu_header.php
  composer.json
  composer.lock
  config/config_type_absence.php
  config/index.php
  edition/Fonctions.php
  hr/Fonctions.php
  hr/hr_index.php
  hr/hr_liste_planning.php
  includes/SQL.php
  includes/fonction.php
  index.php
  package-lock.json
  package.json
  responsable/resp_index.php
  responsable/resp_liste_planning.php
  responsable/resp_modif_planning.php
  utilisateur/user_index.php
Labels: Fonctionnalité, Système, À tester

#768 Prise de congés avec accent
  App/Views/Configuration/Type_Absence/Liste.php
  config/Fonctions.php
  config/config_type_absence.php
  config/index.php
  responsable/resp_cloture_exercice.php
Labels: Bug

#767 InnoDB pour tous !
  App/Patchs/Installation/1.10.0.sql
  App/Patchs/Installation/1.8.0.sql
  App/Patchs/Maj/1.10.0.sql
  App/Patchs/Maj/1.13.1.sql
  App/Patchs/Maj/1.8.1.sql
  App/Patchs/Maj/1.9.0.sql
  admin/admin_index.php
  edition/Fonctions.php
  hr/hr_index.php
  responsable/resp_index.php
  utilisateur/user_index.php
Labels: Amélioration, Système
