Repository libertempo/web, pull requests merged in 2019-07, with the labels that each got.

#822 Lock button
  Public/Assets/Js/reboot.js
Labels: Amélioration, Système, javascript

#806 Cloture d'exercice, gestion des reliquats et traitement des jours fériés français. Fix #418
  App/Libraries/Configuration.php
  App/Patchs/Maj/1.13.4.sql
  App/ProtoControllers/HautResponsable/ClotureExercice.php
  App/ProtoControllers/Responsable/Traitement/Conge.php
  App/ProtoControllers/Utilisateur.php
  App/Tools/locale/fr_FR/LC_MESSAGES/php-conges.po
  App/Tools/setJoursFeries.php
  App/Views/ClotureExercice/ClotureGlobale.php
  Makefile
  Tests/Units/App/ProtoControllers/HautResponsable/ClotureExercice.php
  hr/Fonctions.php
  hr/hr_cloture_year.php
  hr/hr_jours_chomes.php
  includes/fonction.php
  responsable/Fonctions.php
  responsable/resp_cloture_exercice.php
Labels: Amélioration, Métier, À documenter

#828 Ignorer les congés annulés dans l'export ICS
  export/Fonctions.php
Labels: Métier, À tester

#838 erreur lors de l'ajout de congés
  hr/hr_ajout_conges.php
Labels: Bug

#837 Fix #817
  includes/fonction.php
Labels: Bug
