Repository libertempo/web, pull requests merged in 2019-08, with the labels that each got.

#814 authentification CAS
  App/Patchs/Maj/1.13.3.sql
  App/Tools/libraries
  App/Tools/update
  includes/fonction.php
  index.php
Labels: Bug, À documenter

#840 [métier] saisie des heures additionnelles dans le passé
  App/ProtoControllers/Employe/Heure/Additionnelle.php
Labels: Amélioration, Métier

#827 Utilisation de vue pour la création d'employé
  App/Libraries/Configuration.php
  App/ProtoControllers/HautResponsable/Utilisateur.php
  App/Views/Groupe/Edition.php
  App/Views/HautResponsable/Employe/Ajout.php
  edition/Fonctions.php
  hr/hr_ajout_user.php
  package.json
Labels: Amélioration, Système
